### ISSUE TITLE
Clarification for Ubuntu version compatibility

### ISSUE THREAD

**Issue by tmlmt** [LattePandaTeam/LattePanda-Mu#10]
The Mu docs lists both Ubuntu 22.04 (with HWE kernel) and Ubuntu 24.04 in the [Official Support ](https://docs.lattepanda.com/content/mu_edition/os_compatible/#official-support) list but only lists Ubuntu 22.04.2 as having been tested / in the "[Compatible list](https://docs.lattepanda.com/content/mu_edition/os_compatible/#compatible-list)"

1. Could you clarify whether the Mu is compatible with 24.04 ?
2. What is the consequence of not installing the HWE Kernel on 22.04? Also, the 24.04 has [no HWE kernel](https://ubuntu.com/kernel/lifecycle) yet, what's the consequence of that on using the Mu?

**Comment by alphaarea** [comment]
1. The compatibility list only lists the oldest versions that are compatible with LattePanda Mu, newer versions will not be tested again. Ubuntu 24.04 should be fully compatible.
2. The HWE kernel is a new version of the kernel that Ubuntu has ported to older systems to support the latest hardware. Since Ubuntu 22.04 was released before LattePanda Mu, HWE needs to be enabled to support the latest hardware.  
    Ubuntu 24.04 was released with full support for LattePanda Mu, so installing on LattePanda Mu with or without WHE does not affect its performance.  
    Ubuntu 24.04 is still the latest Ubuntu distribution and therefore does not have an HWE kernel.

Regardless of which Linux distribution you want to install, make sure that the kernel version is not lower than 6.1 to be compatible with LattePanda Mu.

**Comment by tmlmt** [comment]
Couldn't be clearer! Thank you @alphaarea 👍
(It may be worth adding some of that wording on the docs page? Or worst case, people may end up visiting this one 😊)
